valor = int(input('Valor: '))
print('Tabuada do valor {} é '.format(valor))
print('{} x 1 = {:2}'.format(valor, valor * 1))
print('{} x 2 = {:2}'.format(valor, valor * 2))
print('{} x 3 = {:2}'.format(valor, valor * 3))
print('{} x 4 = {:2}'.format(valor, valor * 4))
print('{} x 5 = {:2}'.format(valor, valor * 5))
print('{} x 6 = {:2}'.format(valor, valor * 6))
print('{} x 7 = {:2}'.format(valor, valor * 7))
print('{} x 8 = {:2}'.format(valor, valor * 8))
print('{} x 9 = {:2}'.format(valor, valor * 9))
print('{} x 10 = {:2}'.format(valor, valor * 10))
